/** PLUS ACTION */
export const APP_PLUS_REQUEST = 'APP_PLUS_REQUEST';
export const APP_PLUS_SUCCESS = 'APP_PLUS_SUCCESS';
export const APP_PLUS_FAILURE = 'APP_PLUS_FAILURE';

/** MINUS ACTION */
export const APP_MINUS_REQUEST = 'APP_MINUS_REQUEST';
export const APP_MINUS_SUCCESS = 'APP_MINUS_SUCCESS';
export const APP_MINUS_FAILURE = 'APP_MINUS_FAILURE';

export const RESET_STATE = 'RESET_STATE';
